### ISSUE TITLE
Undefined symbols error when building with ML functions enabled in 9.1.1

### ISSUE THREAD

**Issue by darxmac** [EddyVerbruggen/nativescript-plugin-firebase#1391]
After upgrading to 9.1.1 the project fails to build with the following error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FBMLx_GPBEnumArray", referenced from:
      objc-class-ref in FirebaseMLVision(FIRVisionBarcodeDetectorOptions_ffa4c7452d027cd9879e78f98c758129.o)
      objc-class-ref in FirebaseMLVision(FIRVisionBarcodeDetector_97107a20f82168ee45e78e87a60ac939.o)
  "_OBJC_CLASS_$_FBMLx_GMVBarcodeInitializationOptions", referenced from:
      objc-class-ref in FirebaseMLVision(FIRVisionBarcodeDetectorOptions_ffa4c7452d027cd9879e78f98c758129.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **
```

Building without ML functions enabled (i have just enabled barcode reading) work, as does downgrading to 9.0.4 (with ML enabled)

Any ideas ?

**Comment by EddyVerbruggen** [comment]
Hmm.. I don't experience that. Just to be sure: did you clean the platforms folder after bumping the plugin version?

**Comment by darxmac** [comment]
Hi, yes, clean platforms folder. Updated pods with `pod repo update` just to be sure, but still an issue.

**Comment by darxmac** [comment]
I tried to enable everything in `firebase.nativescript.json` except firestore, and now it builds. If i enable firestore i get another error that i will save for a new issue

**Comment by jlooper** [comment]
I just hit this. New project with a new installation of this plugin, and using custom trained ML models. I imagine it's a change for 9.1.1 and maybe an Xcode incompatibility. Still trying to build after pinning to 9.0.4. I'll check back in!

**Comment by jlooper** [comment]
Indeed, pinning to 9.0.4 did it. Gonna stick with that now, as time presses :)

**Comment by cecrs** [comment]
Same issue here - pinning to 9.0.4 fixed it for me as well.

**Comment by darxmac** [comment]
Enabling and disabling different features give a few fun errors during build, I have not found a pattern but for now I have a combination that builds.

**Comment by EddyVerbruggen** [comment]
Hmm, this is reported in the Firebase iOS SDK as well: https://github.com/firebase/firebase-ios-sdk/issues/3782

They say it's resolved in 6.8.0 (which was released quite recently) so I'll assume that will fix it for use as well. I'm working on said release.
