### ISSUE TITLE
firebase.admob.showBanner fails with an exception on iOS after update

### ISSUE THREAD

**Issue by MustafaCa** [EddyVerbruggen/nativescript-plugin-firebase#1248]
Hi Eddy,

After updating xcode to 10.2, iOS SDK to 12.2 and TNS to the latest, I started to get several warnings similar to the following:

`      non-portable path to file '<protobuf/Timestamp.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
 #import <Protobuf/Timestamp.pbobjc.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         <protobuf/Timestamp.pbobjc.h>
1 warning generated.`

Even though the app builds successfully, it fails with the following exception when firebase.admon.showBanner is called. 

`CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/admob/admob.js:56:24: 'Error in firebase.admob.showBanner: TypeError: GADRequest.request is not a function. (In \'GADRequest.request()\', \'GADRequest.request\' is undefined)'`

Android version of the app works fine. Previously built iOS app also works fine.

firebase.nativescript.json has `"admob" : true`

Any suggestions?

Thanks,
Mustafa.

**Comment by EddyVerbruggen** [comment]
Did you remove the platforms/ios folder after updating everything?

**Comment by MustafaCa** [comment]
> Did you remove the platforms/ios folder after updating everything?

Yes, I did, and in fact I did it several times. The project always builds with the above mentioned warnings. The the call to showBanner fails with the same error.

**Comment by MustafaCa** [comment]
OK, I found a solution for the issue. But it is not a permanent one.
In the Podfile I commented the line with the latest version for Firebase/Core and added a new line with an earlier version, 
```
# pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Core', '~> 5.0.0'

```
Then 

```
tns platform remove ios
tns build ios

```

The above change in the Podfile causes even more warnings, but build succeeds and showBanner works fine.

Hope it helps someone else.
