### ISSUE TITLE
firebase.getValue() is not a function

### ISSUE THREAD

**Issue by FrancoisGayraud** [EddyVerbruggen/nativescript-plugin-firebase#567]
Hi,

I work with the 4.1.1 version of this plugin and I want to get a value in my database.
I have a  "TypeError: firebase.getValue() is not a function".

Any ideas?

**Comment by EddyVerbruggen** [comment]
Duplicate of #556
