### ISSUE TITLE
JS: ERROR Error: Uncaught (in promise): TypeError: firebase.uploadFile is not a function JS: TypeError: firebase.uploadFile is not a function

### ISSUE THREAD

**Issue by JaganJonnala** [EddyVerbruggen/nativescript-plugin-firebase#896]
JS: ERROR Error: Uncaught (in promise): TypeError: firebase.uploadFile is not a function
JS: TypeError: firebase.uploadFile is not a function

![image](https://user-images.githubusercontent.com/10844009/45155521-e6fac500-b1f8-11e8-863b-fe23b97a4b24.png)
when i tried to upload a file to firebase storage. It was working code actually when i upgraded nativescript-plugin-firebase to 6.7.0 (from 6.1.1)
its behaving like this can you please help me out

**Comment by JaganJonnala** [comment]
Issue resolved you have seperated the storage to another folder may be. i have added
firebase.storage.uploadFile() thats it
