### ISSUE TITLE
Storage exception with file upload

### ISSUE THREAD

**Issue by xerotolerant** [EddyVerbruggen/nativescript-plugin-firebase#151]
I am trying to upload a file to firebase.
my code is 

```
public uploadPhoto(fileUri: string): void {
    var fileUri = "/storage/emulated/0/Download/sesame-noodles.jpg"
    firebase.uploadFile({
      remoteFullPath: "/profile_pic/profile.png",
      localFullPath: fileUri

    }).then(
      (success) => {
        console.log(JSON.stringify(success));
      },
      (error) => {
          console.log("Error: " + error);
      })
  }

```

The error i get is 
`
Error: Upload failed. com.google.firebase.storage.StorageException: An unknown error occurred, please check the HTTP result code and inner exception for server response.
`

**Comment by EddyVerbruggen** [comment]
Could be a few things as my Google search indicates. For instance: the user needs to be logged in ("the default security rules for storage buckets require you to sign in with firebase authentication").

What have you found on the web and tried already? Btw in my tests I don't use a leading '/' for the remoteFullPath, but I doubt that matters.

**Comment by xerotolerant** [comment]
Right now on the web at large i see nothing useful. All the other reaults
have specific errors and not this unknown one. Also, i get different errors
on ios and android. On ios it says that the file cannot be found.

```
CONSOLE LOG file:///app/views/createProfile/createProfile.js:27:24: uri:
8A871F94-044D-48F1-A10D-ABDB2A74D1C0/L0/001
CONSOLE LOG file:///app/views/createProfile/createProfile.js:28:24:
fileuri: file:///var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG
2016-10-05 15:09:34.268 ExerClub[748:316422] Body file is unreachable:
/8A871F94-044D-48F1-A10D-ABDB2A74D1C0/L0/001
  Error Domain=NSCocoaErrorDomain Code=260 "The file “001” couldn’t be
opened because there is no such file."
UserInfo={NSURL=8A871F94-044D-48F1-A10D-ABDB2A74D1C0/L0/001 -- file:///,
NSFilePath=/8A871F94-044D-48F1-A10D-ABDB2A74D1C0/L0/001,
NSUnderlyingError=0x15e940760 {Error Domain=NSPOSIXErrorDomain Code=2 "No
such file or directory"}}

```

Except the file is being shown in the view. without problems

**Comment by EddyVerbruggen** [comment]
Well that should be yours to fix I guess. [Take a look at the demo app I tested with](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo/blob/master/Firebase/app/main-view-model.js#L645-L651) to see how I resolved the local file.

**Comment by xerotolerant** [comment]
It might have something to do with how the imagepicker plugin formats the uri strings

`CONSOLE LOG **file:///**app/views/createProfile/createProfile.js:28:24: fileuri: file:///var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG
2016-10-05 15:57:26.216 ExerClub[771:326725] Body file is unreachable: /file:/var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG
  Error Domain=NSCocoaErrorDomain Code=260 "The file “IMG_0002.JPG” couldn’t be opened because there is no such file." UserInfo={NSURL=file:/var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG -- file:///, NSFilePath=/file:/var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG, NSUnderlyingError=0x1261d0430 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2016-10-05 15:57:26.441: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=0 "(null)"`

That's the error on ios.

**Comment by EddyVerbruggen** [comment]
I'd appreciate if you can narrow it down to a problem with the plugin or a problem with the path. Just look at the demo code I linked to and see if that works for you. If so try to figure out what path you need to provide to make Firebase happy.

**Comment by xerotolerant** [comment]
Ok I figured it out. The issue has something to do with marshmallow's new runtime permissions. 
I had to manually enable storage permissions on android. I haven't re-tested it on ios yet however on android 6.0+ you have to 
1) enable file permissions for the application
2) use the fs.File.fromPath method. 
Thanks.

PS. The app example still does not work on 6.0.1 without the permissions, so it was not just the other plugin.

**Comment by xerotolerant** [comment]
I reopened the issue because though I get it working on android I haven't gotten it to work on iOS.

`CONSOLE LOG file:///app/shared/user-view-model/user-view-model.js:62:20: fileUri: file:///var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG
CONSOLE LOG file:///app/views/createProfile/createProfile.js:34:20: error: NSErrorWrapper: You don’t have permission to save the file “100APPLE” in the folder “DCIM”.
`

I had to manually enable the file access on android but I can't figure out where to do that on iOS. 
Also does anybody know a way to request that kind of permission explicitly? Searching the nativescript docs doesn't seem to get me anything.

**Comment by EddyVerbruggen** [comment]
Please try uploading a file from within the app folder as shown in the demo app and confirm that works first. Please narrow this down first.

**Comment by xerotolerant** [comment]
More testing.
 I cloned the demo app, init successful, login succesful.
for some strange reason the uploadFile method is less functional than in my version. The doUploadFile method runs when the button is pressed (I put a console log in). However there is no log or anything else afterward. no response after there.

**Comment by EddyVerbruggen** [comment]
OK, reopen with additional info if you're still stuck please.

**Comment by xerotolerant** [comment]
I am still stuck but I have more information now.
The upload is successful if the file is within the app folder as in your example.
The image picker can select and display the image thumbnails as expected. 

however these stack posts show similar issues to what I'm having. They are however using swift and the native uipicker element directly

**Comment by xerotolerant** [comment]
I found a solution after much searching
```

private selectImage(context){
    context.authorize()
      .then(() => {return context.present()})
      .then((selection) => {
        selection.forEach((selected) => {
          selected.getImage()
            .then((imageSource) => {
              var appPath = fs.knownFolders.currentApp().path;
              var profilePath = "/img/profile.jpg";
              var filePath = fs.path.join(appPath, profilePath);
              var saved = imageSource.saveToFile(filePath, enums.ImageFormat.jpeg);
              console.log(`item saved:${saved}`);
              console.log("FilePath: " + filePath);
              console.log("Image source " + JSON.stringify(imageSource));
            },
            (error) => {
              console.log("error");
            })
        })
      })
  }
```

The key is to get the actual image file first using the getImage() function

**Comment by d3mac123** [comment]
@xerotolerant do you mind to share your entire code? I am trying to fix (the same original problem of yours) my issue but I keep getting error messages. 

I have tried to use fromFile, fromAssets, etc...

Here's my code:
```
var platform = require("platform");
var fs = require("file-system");
var imageSource = require("image-source");
var imagepickerModule = require("nativescript-imagepicker");
```

...code continues...
```
function startSelection(context) {
   context.authorize()
      .then(() => {return context.present()})
      .then((selection) => {
         selection.forEach((selected) => {
            selected.getImage()
                .then((imageSource) => {
                    var appPath = fs.knownFolders.currentApp().path;
                    var a = selected.fileUri;
                    var picExt = a.substr(a.length-3, a.length).toLowerCase()
                    var profilePath = "/img/photo."+picExt;
                    var filePath = fs.path.join(appPath, profilePath);
                     console.log("File Path:"+filePath)
                     var saved = imageSource.saveToFile(filePath, "jpeg");
                     console.log("item saved:"+saved);
                     console.log("FilePath: " + filePath);
                     console.log("Image source " + JSON.stringify(imageSource));
                 },
                 (error) => {
                     console.log("error");
                  })
            })
        })
}
```
