### ISSUE TITLE
JS: Error in firebase.init: TypeError: gson(...).toJson is not a function

### ISSUE THREAD

**Issue by vinayvnvv** [EddyVerbruggen/nativescript-plugin-firebase#434]
When i run the app its throwing a error - 
JS: Error in firebase.init: TypeError: gson(...).toJson is not a function

pls help me

**Comment by caferrari** [comment]
I am getting the same error here =/

**Comment by EddyVerbruggen** [comment]
Can you plz check if another 4.0.x version behaves differently?

**Comment by Lacos247** [comment]
Same issue with 4.0.4. I had hoped it will fix my background notfications problem (if app is killed, issue #422 ) on android. Version 4.0.3 seems not to produce this error.

**Comment by EddyVerbruggen** [comment]
Hmm, just tried 4.0.4 again. No issues for me with `gson`. I simply created a new app, added the plugin, and ran init. Anything special I need to do on Android to produce the error?

**Comment by NathanWalker** [comment]
@EddyVerbruggen I also see this with `4.0.4`, here is what my init looks like:
```
      const initOptions: TNSFirebase.InitOptions = {
            onAuthStateChanged: (data) => {
                this._log.debug('Firebase onAuthStateChanged:', data.loggedIn);
                this.isFirebaseLoggedIn = data.loggedIn;
            },
        };

        this._firebase.init(initOptions).then((instance) => {
            this._log.debug('Firebase plugin initialized.');
        }, (error) => {
            this._log.debug('Firebase plugin initialization failed.');
        });
```

**Comment by NathanWalker** [comment]
Worth noting that I'm using this in a NativeScript for Angular project specifically and the firebase.init routine is called very early in an Angular Injectable service which is constructed as part of a core set of modules in the app if that helps at all.

**Comment by caferrari** [comment]
Just tried it again:

```
JS: Error in firebase.init: TypeError: gson(...).toJson is not a function
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: firebase.init error: TypeError: gson(...).toJson is not a function
```

**Comment by EddyVerbruggen** [comment]
Can I clone a project that reproduces this? And/or is the same error present with 4.0.3?

**Comment by NathanWalker** [comment]
My project is private and not owned by me so can't share it - however I will also note I experience this with GenyMotion emulator (which has Google play services fully setup) so not sure if related to emulator or not? Or does an extra config file need to be changed to ensure com.google.gson is loaded?

**Comment by caferrari** [comment]
Mine is private also, i'll try to clean it up and make a repository..

**Comment by caferrari** [comment]
there it is:

https://github.com/caferrari/nativescript-seed

**Comment by NathanWalker** [comment]
@EddyVerbruggen curious if you see a potential cause at this point? If you aren't looking into I was going to fork and try a couple things but didn't want to overstep ;)

**Comment by EddyVerbruggen** [comment]
@caferrari Cloning your repo and doing `tns run android` reproduces the error, thanks!

I'll take a look.

@NathanWalker Thanks for the offer. I'll try to look at it today.

**Comment by EddyVerbruggen** [comment]
I think 4.0.3 works fine, so please use that in the meanwhile. This must have been caused by PR #424 which added lazy loading to the gson lib.

**Comment by EddyVerbruggen** [comment]
Yeah that `lazy` implementation is not perfect. There are 2 methods using the `lazy` function. Since that function acts like a singleton it caches the first call and always uses the result of that invocation. In this case the `messagingEnabled` call (with value `true`) is cached and returned when a `Gson` object instance is expected.

**Comment by EddyVerbruggen** [comment]
OK, doing `new lazy` instead of `lazy` [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/4b0dfb240a72ab9c01f7612cac4fb057bfa5e737/firebase.android.js#L27) and [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/4b0dfb240a72ab9c01f7612cac4fb057bfa5e737/firebase.android.js#L31) fixes the problem. The lazy result will still be cached, but usages won't bite each other.

I have to look at another issue tomorrow and will release 4.0.5 afterwards.

Thanks again for the cooperation!

**Comment by NathanWalker** [comment]
Excellent work thanks @EddyVerbruggen !
